INSERT INTO PHONE_TYPE (phone_type_name) VALUES ('CELL');
INSERT INTO PHONE_TYPE (phone_type_name) VALUES ('HOME');
INSERT INTO PHONE_TYPE (phone_type_name) VALUES ('OFFICE');
INSERT INTO PHONE_TYPE (phone_type_name) VALUES ('FAX');
INSERT INTO PHONE_TYPE (phone_type_name) VALUES ('LODGE');
INSERT INTO ADDRESS (STREET_ADDRESS_1,STREET_ADDRESS_2, CITY, STATE, ZIP) VALUES ('1025 Robert Drive', 'Suite 101','Maryville','IL', '62062-6264');
INSERT INTO PHONE (area_code, extension, phone_number,phone_type_phone_type_id) VALUES ('618','','6165801',1);
INSERT INTO PERSON (first_name, last_name, middle_init, ADDRESS_ADDRESS_ID) VALUES ('RICHARD', 'HAYS','N', 1);
INSERT INTO PERSON (first_name, last_name, middle_init) VALUES ('JOE','SMITH','');
INSERT INTO PERSON (first_name, last_name, middle_init) VALUES ('JANE','DOE','');
--INSERT INTO ADDRESS (STREET_ADDRESS_1,STREET_ADDRESS_2, CITY, STATE, ZIP) VALUES ('1025 Robert Drive', 'Suite 101','Maryville','IL', '62062-6264');
--INSERT INTO person_address (person_person_id, address_address_id) VALUES (2,1);
INSERT INTO organization (name, ADDRESS_ADDRESS_ID) VALUES ('NEILSON', 1);
--INSERT INTO organization_addresses (organization_org_id, addresses_address_id) VALUES (1,1);